/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Trader Edge API specification
 * OpenAPI spec version: 0.1.0
 */
/**
 * @nullable
 */
export type InstrumentDirection = (typeof InstrumentDirection)[keyof typeof InstrumentDirection] | null;
export declare const InstrumentDirection: {
    readonly BUY: "BUY";
    readonly SELL: "SELL";
};
//# sourceMappingURL=instrumentDirection.d.ts.map