/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Trader Edge API specification
 * OpenAPI spec version: 0.1.0
 */
export type InstrumentCategory = (typeof InstrumentCategory)[keyof typeof InstrumentCategory];
export declare const InstrumentCategory: {
    readonly market: "market";
    readonly crypto: "crypto";
};
//# sourceMappingURL=instrumentCategory.d.ts.map