/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * Trader Edge API specification
 * OpenAPI spec version: 0.1.0
 */
export type TradeDecisionDirection = (typeof TradeDecisionDirection)[keyof typeof TradeDecisionDirection];
export declare const TradeDecisionDirection: {
    readonly BUY: "BUY";
    readonly SELL: "SELL";
};
//# sourceMappingURL=tradeDecisionDirection.d.ts.map